use Restaurant
go

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Ingredients
WAITFOR DELAY '00:00:04'
SELECT * FROM Ingredients
COMMIT TRAN

--DELETE FROM INGREDIENTS WHERE IngredientName = 'Pepper'