use Restaurant
go

ALTER DATABASE Restaurant SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE Customers SET Address = 'Cluj Napoca, Romania' WHERE CID = 1
WAITFOR DELAY '00:00:05'
COMMIT TRAN

--SELECT * FROM Customers

--ALTER DATABASE Restaurant SET ALLOW_SNAPSHOT_ISOLATION OFF
--UPDATE Customers SET Address = 'TG MURES' WHERE CID = 1
--SELECT * FROM Customers